const DO_LOGIN = 'DO_LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const SETEMAIL = 'SETEMAIL';
const SETPASSWORD = 'SETPASSWORD';
const DASHBOARD_LOAD  = 'DASHBOARD_LOAD';
const DASHBOARD_LOAD_SUCCESS = 'DASHBOARD_LOAD_SUCCESS'

export  {
    DO_LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    SETEMAIL,
    SETPASSWORD,
    DASHBOARD_LOAD,
    DASHBOARD_LOAD_SUCCESS
}